/**
 * Static fixtures used when the app is built with VITE_DEMO=1 (e.g. the GitHub
 * Pages build). They let the dashboard + editor render a real, interactive
 * diagram with no backend. Editing works in-session via the Zustand store, but
 * nothing is persisted — refresh resets to this seed.
 *
 * Only `app`, `system`, and `custom` node types have canvas components today,
 * so the fixture sticks to those.
 */
import type { Company, Diagram, DiagramDetail } from '@system-map/shared'

const TS = '2026-05-01T12:00:00.000Z'

const COMPANY_ID = 'demo-co'

export const demoCompanies: Company[] = [
  { id: COMPANY_ID, name: 'Acme Inc.', slug: 'acme', createdAt: TS, updatedAt: TS },
]

export const demoDiagrams: Diagram[] = [
  {
    id: 'demo-payments',
    companyId: COMPANY_ID,
    name: 'Payments platform',
    description: 'How a charge flows from the apps through our services to Stripe and Postgres.',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'demo-onboarding',
    companyId: COMPANY_ID,
    name: 'Onboarding flow',
    description: 'What happens when a new user signs up.',
    createdAt: TS,
    updatedAt: TS,
  },
]

const payments: DiagramDetail = {
  id: 'demo-payments',
  companyId: COMPANY_ID,
  name: 'Payments platform',
  description: 'How a charge flows from the apps through our services to Stripe and Postgres.',
  createdAt: TS,
  updatedAt: TS,
  layers: [
    {
      id: 'l-core',
      diagramId: 'demo-payments',
      name: 'Core services',
      color: '#D4471F',
      order: 0,
      visible: true,
    },
    {
      id: 'l-ext',
      diagramId: 'demo-payments',
      name: 'Integrations',
      color: '#4F46E5',
      order: 1,
      visible: true,
    },
  ],
  views: [],
  nodes: [
    {
      id: 'n-customer',
      diagramId: 'demo-payments',
      layerId: 'l-ext',
      type: 'custom',
      positionX: 20,
      positionY: 260,
      data: {
        label: 'Customer',
        fields: {},
        color: '#4F46E5',
        description: 'End user on web or mobile',
      },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-web',
      diagramId: 'demo-payments',
      layerId: 'l-core',
      type: 'app',
      positionX: 280,
      positionY: 120,
      data: { label: 'Web App', category: 'Frontend', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-mobile',
      diagramId: 'demo-payments',
      layerId: 'l-core',
      type: 'app',
      positionX: 280,
      positionY: 380,
      data: { label: 'Mobile App', category: 'Frontend', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-gw',
      diagramId: 'demo-payments',
      layerId: 'l-core',
      type: 'system',
      positionX: 560,
      positionY: 250,
      data: { label: 'api-gateway', category: 'Edge', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-billing',
      diagramId: 'demo-payments',
      layerId: 'l-core',
      type: 'system',
      positionX: 850,
      positionY: 110,
      data: { label: 'billing-svc', category: 'Payments', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-auth',
      diagramId: 'demo-payments',
      layerId: 'l-core',
      type: 'system',
      positionX: 850,
      positionY: 390,
      data: { label: 'auth-svc', category: 'Identity', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-db',
      diagramId: 'demo-payments',
      layerId: 'l-core',
      type: 'system',
      positionX: 1150,
      positionY: 250,
      data: { label: 'postgres', category: 'Datastore', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-stripe',
      diagramId: 'demo-payments',
      layerId: 'l-ext',
      type: 'app',
      positionX: 1150,
      positionY: 30,
      data: { label: 'Stripe', category: 'Payments', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'n-segment',
      diagramId: 'demo-payments',
      layerId: 'l-ext',
      type: 'app',
      positionX: 850,
      positionY: 590,
      data: { label: 'Segment', category: 'Analytics', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
  ],
  edges: [
    {
      id: 'e1',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-customer',
      targetNodeId: 'n-web',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'data',
      label: 'visits',
      data: { direction: 'one_way' },
    },
    {
      id: 'e2',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-customer',
      targetNodeId: 'n-mobile',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'data',
      label: 'uses',
      data: { direction: 'one_way' },
    },
    {
      id: 'e3',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-web',
      targetNodeId: 'n-gw',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'api',
      label: 'REST',
      data: { direction: 'two_way' },
    },
    {
      id: 'e4',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-mobile',
      targetNodeId: 'n-gw',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'api',
      label: 'REST',
      data: { direction: 'two_way' },
    },
    {
      id: 'e5',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-gw',
      targetNodeId: 'n-billing',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'api',
      label: 'charge',
      data: { direction: 'two_way' },
    },
    {
      id: 'e6',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-gw',
      targetNodeId: 'n-auth',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'api',
      label: 'verify',
      data: { direction: 'two_way' },
    },
    {
      id: 'e7',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-billing',
      targetNodeId: 'n-stripe',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'cash',
      label: 'settle',
      data: { direction: 'two_way' },
    },
    {
      id: 'e8',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-billing',
      targetNodeId: 'n-db',
      sourceHandle: 'right',
      targetHandle: 'top',
      flowType: 'data',
      label: 'writes',
      data: { direction: 'one_way' },
    },
    {
      id: 'e9',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-auth',
      targetNodeId: 'n-db',
      sourceHandle: 'right',
      targetHandle: 'bottom',
      flowType: 'data',
      label: 'reads',
      data: { direction: 'one_way' },
    },
    {
      id: 'e10',
      diagramId: 'demo-payments',
      sourceNodeId: 'n-gw',
      targetNodeId: 'n-segment',
      sourceHandle: 'bottom',
      targetHandle: 'top',
      flowType: 'event',
      label: 'track',
      data: { direction: 'one_way' },
    },
  ],
}

const onboarding: DiagramDetail = {
  id: 'demo-onboarding',
  companyId: COMPANY_ID,
  name: 'Onboarding flow',
  description: 'What happens when a new user signs up.',
  createdAt: TS,
  updatedAt: TS,
  layers: [
    {
      id: 'l2-main',
      diagramId: 'demo-onboarding',
      name: 'Main',
      color: '#047857',
      order: 0,
      visible: true,
    },
  ],
  views: [],
  nodes: [
    {
      id: 'o-user',
      diagramId: 'demo-onboarding',
      layerId: 'l2-main',
      type: 'custom',
      positionX: 40,
      positionY: 150,
      data: { label: 'New user', fields: {}, color: '#047857' },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'o-app',
      diagramId: 'demo-onboarding',
      layerId: 'l2-main',
      type: 'app',
      positionX: 320,
      positionY: 150,
      data: { label: 'Onboarding App', category: 'Frontend', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'o-email',
      diagramId: 'demo-onboarding',
      layerId: 'l2-main',
      type: 'app',
      positionX: 620,
      positionY: 40,
      data: { label: 'SendGrid', category: 'Email', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'o-crm',
      diagramId: 'demo-onboarding',
      layerId: 'l2-main',
      type: 'app',
      positionX: 620,
      positionY: 260,
      data: { label: 'HubSpot', category: 'CRM', fields: {} },
      createdAt: TS,
      updatedAt: TS,
    },
  ],
  edges: [
    {
      id: 'oe1',
      diagramId: 'demo-onboarding',
      sourceNodeId: 'o-user',
      targetNodeId: 'o-app',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'data',
      label: 'signs up',
      data: { direction: 'one_way' },
    },
    {
      id: 'oe2',
      diagramId: 'demo-onboarding',
      sourceNodeId: 'o-app',
      targetNodeId: 'o-email',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'event',
      label: 'welcome email',
      data: { direction: 'one_way' },
    },
    {
      id: 'oe3',
      diagramId: 'demo-onboarding',
      sourceNodeId: 'o-app',
      targetNodeId: 'o-crm',
      sourceHandle: 'right',
      targetHandle: 'left',
      flowType: 'event',
      label: 'create lead',
      data: { direction: 'one_way' },
    },
  ],
}

const detailsById: Record<string, DiagramDetail> = {
  'demo-payments': payments,
  'demo-onboarding': onboarding,
}

/** Falls back to the payments map so any diagram id resolves to something. */
export function getDemoDiagram(id: string): DiagramDetail {
  return detailsById[id] ?? payments
}
