/**
 * AUTO-GENERATED demo fixtures (apps/web/scripts/genDemoData.ts).
 * Used when built with VITE_DEMO=1 (the GitHub Pages build): the dashboard +
 * editor render these real diagrams with no backend. Editing works in-session
 * via the Zustand store but nothing persists — refresh resets to this seed.
 * Logos are bundled under public/uploads. Regenerate after changing the seed.
 */
import type { Company, Diagram, DiagramDetail } from '@system-map/shared'

export const demoCompanies: Company[] = [
  {
    id: 'demo-co',
    name: 'Acme Inc.',
    slug: 'acme',
    createdAt: '2026-05-26T15:07:26.314Z',
    updatedAt: '2026-05-26T15:07:26.314Z',
  },
]

export const demoDiagrams: Diagram[] = [
  {
    id: 'project-atlantic',
    companyId: 'demo-co',
    name: 'Project Atlantic',
    description: "Lloyd's syndicate target operating model — current vs. future state.",
    createdAt: '2026-05-28T13:46:52.431Z',
    updatedAt: '2026-05-28T13:46:52.431Z',
  },
  {
    id: 'demo-payments',
    companyId: 'demo-co',
    name: 'Payments platform',
    description: 'How a charge flows from the apps through our services to Stripe and Postgres.',
    createdAt: '2026-05-26T15:07:26.322Z',
    updatedAt: '2026-05-27T21:56:27.333Z',
  },
  {
    id: 'demo-onboarding',
    companyId: 'demo-co',
    name: 'Onboarding flow',
    description: 'What happens when a new user signs up.',
    createdAt: '2026-05-26T15:07:26.343Z',
    updatedAt: '2026-05-26T15:07:26.343Z',
  },
]

const detailsById: Record<string, DiagramDetail> = {
  'project-atlantic': {
    id: 'project-atlantic',
    companyId: 'demo-co',
    name: 'Project Atlantic',
    description: "Lloyd's syndicate target operating model — current vs. future state.",
    createdAt: '2026-05-28T13:46:52.431Z',
    updatedAt: '2026-05-28T13:46:52.431Z',
    layers: [
      {
        id: 'l-atl-core',
        diagramId: 'project-atlantic',
        name: 'Core platform',
        color: '#475569',
        order: 0,
        visible: true,
      },
      {
        id: 'l-atl-uw',
        diagramId: 'project-atlantic',
        name: 'Underwriting & claims',
        color: '#b45309',
        order: 1,
        visible: true,
      },
      {
        id: 'l-atl-data',
        diagramId: 'project-atlantic',
        name: 'Data & distribution',
        color: '#047857',
        order: 2,
        visible: true,
      },
    ],
    nodes: [
      {
        id: 'atl-brokers',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-data',
        type: 'external_entity',
        positionX: 40,
        positionY: 220,
        width: null,
        height: null,
        data: {
          label: 'Brokers',
          fields: {},
          category: 'Distribution',
          lifecycle: 'existing',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-salesforce',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-data',
        type: 'app',
        positionX: 40,
        positionY: 380,
        width: null,
        height: null,
        data: {
          cost: {
            basis: 'Broker portal',
            currency: 'GBP',
            confidence: 'known',
            monthlyAmount: 200000,
          },
          label: 'Salesforce',
          fields: {},
          vendor: {
            name: 'Salesforce',
            domain: 'salesforce.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/jiKm-o_YtqWAgA6O9hf0I.png',
            category: 'Productivity',
            maturity: 'established',
            fetchedAt: '2026-05-28T13:46:52.697Z',
            description:
              'Salesforce, Inc., is an American cloud-based software company headquartered in San Francisco, California. It is primarily known for its customer relationship management software and related applications which it delivers through a software as a service subscription business model. It also provides software for sales, customer service, marketing automation, e-commerce, analytics, artificial intelligence, agentic AI, and application development.',
            wikipediaUrl: 'https://en.wikipedia.org/wiki/Salesforce',
          },
          category: 'Productivity',
          lifecycle: 'existing',
          lifecycleNotes: 'Broker portal — stays.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-snowflake',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-data',
        type: 'app',
        positionX: 900,
        positionY: 220,
        width: null,
        height: null,
        data: {
          cost: {
            currency: 'GBP',
            confidence: 'known',
            monthlyAmount: 150000,
          },
          label: 'Snowflake',
          fields: {},
          vendor: {
            name: 'Snowflake',
            domain: 'snowflake.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/H79BIU2AoYhXdfyaYa_mH.png',
            category: 'Data & Analytics',
            maturity: 'established',
            fetchedAt: '2026-05-28T13:46:52.742Z',
            description:
              'Snowflake Inc. is an American cloud-based data platform company founded in San Mateo, California, and headquartered in Menlo Park. It operates a platform that supports data analysis and simultaneous access to data sets with minimal latency. It operates on Amazon Web Services, Microsoft Azure, and Google Cloud Platform.',
            wikipediaUrl: 'https://en.wikipedia.org/wiki/Snowflake_Inc.',
          },
          category: 'Data & Analytics',
          lifecycle: 'modifying',
          lifecycleNotes: 'Scaling for new data sources.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-excel',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-uw',
        type: 'app',
        positionX: 320,
        positionY: 70,
        width: null,
        height: null,
        data: {
          cost: {
            basis: 'Excel + M365 licences',
            currency: 'GBP',
            confidence: 'known',
            monthlyAmount: 20000,
          },
          label: 'Microsoft 365',
          fields: {},
          vendor: {
            name: 'Microsoft 365',
            domain: 'microsoft.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/nQMEoV0AP95AttcbEyh19.png',
            category: 'Productivity',
            maturity: 'established',
            fetchedAt: '2026-05-28T13:46:52.772Z',
            description: null,
            wikipediaUrl: null,
          },
          category: 'Productivity',
          lifecycle: 'retiring',
          lifecycleNotes: 'Spreadsheet pricing — retired in favour of hyperexponential.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-send',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-uw',
        type: 'app',
        positionX: 320,
        positionY: 210,
        width: null,
        height: null,
        data: {
          cost: {
            currency: 'GBP',
            confidence: 'estimated',
            monthlyAmount: 600000,
          },
          label: 'Send',
          fields: {},
          vendor: {
            name: 'Send',
            domain: 'send.technology',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/xPfHTiHvFpvj1Oq_2i_Va.png',
            category: 'Underwriter Workbench',
            maturity: 'growth',
            fetchedAt: '2026-05-28T13:46:52.793Z',
            description: null,
            wikipediaUrl: null,
          },
          category: 'Underwriter Workbench',
          lifecycle: 'new',
          lifecycleNotes: 'Underwriter workbench.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-claims',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-uw',
        type: 'custom',
        positionX: 320,
        positionY: 360,
        width: null,
        height: null,
        data: {
          label: 'Manual claims',
          fields: {},
          category: 'Claims handlers',
          lifecycle: 'existing',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-shift',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-uw',
        type: 'app',
        positionX: 320,
        positionY: 510,
        width: null,
        height: null,
        data: {
          cost: {
            currency: 'GBP',
            confidence: 'estimated',
            monthlyAmount: 300000,
          },
          label: 'Shift Technology',
          fields: {},
          vendor: {
            name: 'Shift Technology',
            domain: 'shift-technology.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/wMUM8Nb4zFgkcdUD8w5ir.png',
            category: 'Claims · Fraud',
            maturity: 'growth',
            fetchedAt: '2026-05-28T13:46:52.907Z',
            description: null,
            wikipediaUrl: null,
          },
          category: 'Claims · Fraud',
          lifecycle: 'new',
          lifecycleNotes: 'Claims fraud detection.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-hx',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-uw',
        type: 'app',
        positionX: 600,
        positionY: 430,
        width: null,
        height: null,
        data: {
          cost: {
            currency: 'GBP',
            confidence: 'estimated',
            monthlyAmount: 800000,
          },
          label: 'hyperexponential',
          fields: {},
          vendor: {
            name: 'hyperexponential',
            domain: 'hyperexponential.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/mtKGcovhgkN9I8_tIv9h8.png',
            category: 'Pricing & Rating',
            maturity: 'growth',
            fetchedAt: '2026-05-28T13:46:52.935Z',
            description: null,
            wikipediaUrl: null,
          },
          category: 'Pricing & Rating',
          lifecycle: 'new',
          lifecycleNotes: 'Pricing & rating.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-sapiens',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-core',
        type: 'app',
        positionX: 600,
        positionY: 100,
        width: null,
        height: null,
        data: {
          cost: {
            currency: 'GBP',
            confidence: 'known',
            monthlyAmount: 400000,
          },
          label: 'Sapiens',
          fields: {},
          vendor: {
            name: 'Sapiens',
            domain: 'sapiens.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/BQ7E8B0eeCUyVbGITUd9K.png',
            category: 'Policy Admin',
            maturity: 'established',
            fetchedAt: '2026-05-28T13:46:52.962Z',
            description: null,
            wikipediaUrl: null,
          },
          category: 'Policy Admin',
          lifecycle: 'replacing',
          lifecycleNotes: 'Legacy policy admin — being replaced by Guidewire.',
          replacedByNodeId: 'atl-guidewire',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
      {
        id: 'atl-guidewire',
        diagramId: 'project-atlantic',
        layerId: 'l-atl-core',
        type: 'app',
        positionX: 600,
        positionY: 250,
        width: null,
        height: null,
        data: {
          cost: {
            currency: 'GBP',
            confidence: 'estimated',
            monthlyAmount: 1200000,
          },
          label: 'Guidewire',
          fields: {},
          vendor: {
            name: 'Guidewire',
            domain: 'guidewire.com',
            source: 'live',
            logoUrl: '/uploads/vendor-logos/e-3o7-joe7cz83jNj6LcL.png',
            category: 'Policy Admin',
            maturity: 'established',
            fetchedAt: '2026-05-28T13:46:53.081Z',
            description:
              'Guidewire Software, Inc., commonly Guidewire, is an American software company based in San Mateo, California. It offers an industry platform for property and casualty (P&C) insurance carriers in the U.S. and worldwide.',
            wikipediaUrl: 'https://en.wikipedia.org/wiki/Guidewire_Software',
          },
          category: 'Policy Admin',
          lifecycle: 'new',
          lifecycleNotes: 'Modern policy admin core.',
        },
        createdAt: '2026-05-28T13:46:53.089Z',
        updatedAt: '2026-05-28T13:46:53.089Z',
      },
    ],
    edges: [
      {
        id: 'atl-e1',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-brokers',
        targetNodeId: 'atl-sapiens',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'manual',
        label: 'submissions',
        data: {
          direction: 'one_way',
          lifecycle: 'existing',
        },
      },
      {
        id: 'atl-e2',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-excel',
        targetNodeId: 'atl-sapiens',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'manual',
        label: 'rates',
        data: {
          direction: 'one_way',
          lifecycle: 'retiring',
        },
      },
      {
        id: 'atl-e3',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-claims',
        targetNodeId: 'atl-sapiens',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'manual',
        label: 'claims',
        data: {
          direction: 'one_way',
          lifecycle: 'retiring',
        },
      },
      {
        id: 'atl-e4',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-sapiens',
        targetNodeId: 'atl-snowflake',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'data',
        label: 'policies',
        data: {
          direction: 'one_way',
          lifecycle: 'existing',
        },
      },
      {
        id: 'atl-e5',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-salesforce',
        targetNodeId: 'atl-brokers',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'api',
        label: 'portal',
        data: {
          direction: 'one_way',
          lifecycle: 'existing',
        },
      },
      {
        id: 'atl-e6',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-brokers',
        targetNodeId: 'atl-send',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'api',
        label: 'submissions',
        data: {
          direction: 'one_way',
          lifecycle: 'new',
        },
      },
      {
        id: 'atl-e7',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-send',
        targetNodeId: 'atl-hx',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'api',
        label: 'price',
        data: {
          direction: 'one_way',
          lifecycle: 'new',
        },
      },
      {
        id: 'atl-e8',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-send',
        targetNodeId: 'atl-guidewire',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'api',
        label: 'bind',
        data: {
          direction: 'one_way',
          lifecycle: 'new',
        },
      },
      {
        id: 'atl-e9',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-shift',
        targetNodeId: 'atl-guidewire',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'event',
        label: 'fraud signal',
        data: {
          direction: 'one_way',
          lifecycle: 'new',
        },
      },
      {
        id: 'atl-e10',
        diagramId: 'project-atlantic',
        sourceNodeId: 'atl-guidewire',
        targetNodeId: 'atl-snowflake',
        sourceHandle: null,
        targetHandle: null,
        flowType: 'data',
        label: 'policies',
        data: {
          direction: 'one_way',
          lifecycle: 'new',
        },
      },
    ],
    views: [],
  },
  'demo-payments': {
    id: 'demo-payments',
    companyId: 'demo-co',
    name: 'Payments platform',
    description: 'How a charge flows from the apps through our services to Stripe and Postgres.',
    createdAt: '2026-05-26T15:07:26.322Z',
    updatedAt: '2026-05-27T21:56:27.333Z',
    layers: [
      {
        id: 'l-core',
        diagramId: 'demo-payments',
        name: 'Core services',
        color: '#D4471F',
        order: 0,
        visible: true,
      },
      {
        id: 'l-ext',
        diagramId: 'demo-payments',
        name: 'Integrations',
        color: '#4F46E5',
        order: 1,
        visible: true,
      },
    ],
    nodes: [
      {
        id: 'n-auth',
        diagramId: 'demo-payments',
        layerId: 'l-core',
        type: 'system',
        positionX: 850,
        positionY: 390,
        width: null,
        height: null,
        data: {
          label: 'auth-svc',
          fields: {},
          category: 'Identity',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-customer',
        diagramId: 'demo-payments',
        layerId: 'l-ext',
        type: 'custom',
        positionX: 20,
        positionY: 260,
        width: null,
        height: null,
        data: {
          color: '#4F46E5',
          label: 'Customer',
          fields: {},
          description: 'End user on web or mobile',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-web',
        diagramId: 'demo-payments',
        layerId: 'l-core',
        type: 'app',
        positionX: 275,
        positionY: 120,
        width: null,
        height: null,
        data: {
          label: 'Web App',
          fields: {},
          category: 'Frontend',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-mobile',
        diagramId: 'demo-payments',
        layerId: 'l-core',
        type: 'app',
        positionX: 280,
        positionY: 380,
        width: null,
        height: null,
        data: {
          label: 'Mobile App',
          fields: {},
          category: 'Frontend',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-gw',
        diagramId: 'demo-payments',
        layerId: 'l-core',
        type: 'system',
        positionX: 560,
        positionY: 250,
        width: null,
        height: null,
        data: {
          label: 'api-gateway',
          fields: {},
          category: 'Edge',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-billing',
        diagramId: 'demo-payments',
        layerId: 'l-core',
        type: 'system',
        positionX: 850,
        positionY: 110,
        width: null,
        height: null,
        data: {
          label: 'billing-svc',
          fields: {},
          category: 'Payments',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-db',
        diagramId: 'demo-payments',
        layerId: 'l-core',
        type: 'data_source',
        positionX: 1150,
        positionY: 250,
        width: null,
        height: null,
        data: {
          label: 'postgres',
          fields: {},
          category: 'Datastore',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-stripe',
        diagramId: 'demo-payments',
        layerId: 'l-ext',
        type: 'app',
        positionX: 1150,
        positionY: 30,
        width: null,
        height: null,
        data: {
          label: 'Stripe',
          fields: {},
          category: 'Payments',
          lifecycle: 'existing',
          appearance: {
            iconUrl: 'https://cdn.simpleicons.org/stripe',
          },
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
      {
        id: 'n-segment',
        diagramId: 'demo-payments',
        layerId: 'l-ext',
        type: 'app',
        positionX: 850,
        positionY: 590,
        width: null,
        height: null,
        data: {
          label: 'Segment',
          fields: {},
          category: 'Analytics',
        },
        createdAt: '2026-05-26T15:07:26.333Z',
        updatedAt: '2026-05-27T21:56:27.350Z',
      },
    ],
    edges: [
      {
        id: 'e7',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-billing',
        targetNodeId: 'n-stripe',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'cash',
        label: 'settle',
        data: {
          direction: 'two_way',
        },
      },
      {
        id: 'e8',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-billing',
        targetNodeId: 'n-db',
        sourceHandle: 'right',
        targetHandle: 'top',
        flowType: 'data',
        label: 'writes',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'e9',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-auth',
        targetNodeId: 'n-db',
        sourceHandle: 'right',
        targetHandle: 'bottom',
        flowType: 'data',
        label: 'reads',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'e10',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-gw',
        targetNodeId: 'n-segment',
        sourceHandle: 'bottom',
        targetHandle: 'top',
        flowType: 'event',
        label: 'track',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'e1',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-customer',
        targetNodeId: 'n-web',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'data',
        label: 'visits',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'e2',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-customer',
        targetNodeId: 'n-mobile',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'data',
        label: 'uses',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'e3',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-web',
        targetNodeId: 'n-gw',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'api',
        label: 'REST',
        data: {
          direction: 'two_way',
        },
      },
      {
        id: 'e4',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-mobile',
        targetNodeId: 'n-gw',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'api',
        label: 'REST',
        data: {
          direction: 'two_way',
        },
      },
      {
        id: 'e5',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-gw',
        targetNodeId: 'n-billing',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'api',
        label: 'charge',
        data: {
          direction: 'two_way',
        },
      },
      {
        id: 'e6',
        diagramId: 'demo-payments',
        sourceNodeId: 'n-gw',
        targetNodeId: 'n-auth',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'api',
        label: 'verify',
        data: {
          direction: 'two_way',
        },
      },
    ],
    views: [],
  },
  'demo-onboarding': {
    id: 'demo-onboarding',
    companyId: 'demo-co',
    name: 'Onboarding flow',
    description: 'What happens when a new user signs up.',
    createdAt: '2026-05-26T15:07:26.343Z',
    updatedAt: '2026-05-26T15:07:26.343Z',
    layers: [
      {
        id: 'l2-main',
        diagramId: 'demo-onboarding',
        name: 'Main',
        color: '#047857',
        order: 0,
        visible: true,
      },
    ],
    nodes: [
      {
        id: 'o-user',
        diagramId: 'demo-onboarding',
        layerId: 'l2-main',
        type: 'external_entity',
        positionX: 40,
        positionY: 150,
        width: null,
        height: null,
        data: {
          label: 'New user',
          fields: {},
        },
        createdAt: '2026-05-26T15:07:26.345Z',
        updatedAt: '2026-05-26T15:07:26.345Z',
      },
      {
        id: 'o-app',
        diagramId: 'demo-onboarding',
        layerId: 'l2-main',
        type: 'app',
        positionX: 320,
        positionY: 150,
        width: null,
        height: null,
        data: {
          label: 'Onboarding App',
          fields: {},
          category: 'Frontend',
        },
        createdAt: '2026-05-26T15:07:26.345Z',
        updatedAt: '2026-05-26T15:07:26.345Z',
      },
      {
        id: 'o-email',
        diagramId: 'demo-onboarding',
        layerId: 'l2-main',
        type: 'app',
        positionX: 620,
        positionY: 40,
        width: null,
        height: null,
        data: {
          label: 'SendGrid',
          fields: {},
          category: 'Email',
        },
        createdAt: '2026-05-26T15:07:26.345Z',
        updatedAt: '2026-05-26T15:07:26.345Z',
      },
      {
        id: 'o-crm',
        diagramId: 'demo-onboarding',
        layerId: 'l2-main',
        type: 'app',
        positionX: 620,
        positionY: 260,
        width: null,
        height: null,
        data: {
          label: 'HubSpot',
          fields: {},
          category: 'CRM',
        },
        createdAt: '2026-05-26T15:07:26.345Z',
        updatedAt: '2026-05-26T15:07:26.345Z',
      },
    ],
    edges: [
      {
        id: 'oe1',
        diagramId: 'demo-onboarding',
        sourceNodeId: 'o-user',
        targetNodeId: 'o-app',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'data',
        label: 'signs up',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'oe2',
        diagramId: 'demo-onboarding',
        sourceNodeId: 'o-app',
        targetNodeId: 'o-email',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'event',
        label: 'welcome email',
        data: {
          direction: 'one_way',
        },
      },
      {
        id: 'oe3',
        diagramId: 'demo-onboarding',
        sourceNodeId: 'o-app',
        targetNodeId: 'o-crm',
        sourceHandle: 'right',
        targetHandle: 'left',
        flowType: 'event',
        label: 'create lead',
        data: {
          direction: 'one_way',
        },
      },
    ],
    views: [],
  },
}

/** Falls back to the first diagram so any id resolves to something. */
export function getDemoDiagram(id: string): DiagramDetail {
  return detailsById[id] ?? (Object.values(detailsById)[0] as DiagramDetail)
}
